### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined on switcher.js:34

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#84]
Oh `undefined` my old _nemesis_ how I've ***NOT*** missed you!
![image](https://user-images.githubusercontent.com/194400/31309105-cd427072-ab78-11e7-906b-3bfb8a3f7d41.png)

```
/dwyl/top/node_modules/github-scraper/lib/switcher.js:34
  if(url.match(/\.atom/)) { // feed parser has its own request handler
        ^

TypeError: Cannot read property 'match' of undefined
    at switcher (/dwyl/top/node_modules/github-scraper/lib/switcher.js:34:9)
    at Timeout.<anonymous> (/dwyl/top/3_find_sheeple_who_follow.js:25:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
I'm _so_ tempted to re-write this in Elixir or Haskell ... if _only_ I could _justify_ the _time_!!

**Comment by nelsonic** [comment]
Annoyingly there are a _few_ users who have the word `undefined` in their GitHub `username` 
e.g: https://github.com/undefined and https://github.com/undefined-zola ...

so the line: https://github.com/nelsonic/github-scraper/blob/4c53e804196af546e3899ecb1e92fe3adfc01c45/lib/url_validator.js#L13-L15
```js
  if(!url || url.length === 0 || typeof url === 'undefined' || url.match(/undefined/)){
    return callback(400);
  }
```
in `switcher.js:34` is _always_ going to `400` ... 😞

**Comment by nelsonic** [comment]
Ok I've found quite a few _Jokers_ who think they are _hilarious_ and have the word `undefined` in their GitHub Username. I have _two_ choices:
1. continue to throw an _error_ when `undefined` is in the `url` ❗️ 
2. write a few tests for this condition and _address_ the issue ... 🙄

**Comment by nelsonic** [comment]
`this` _genius_ was _super_ creative with his Username: https://github.com/nullnullundefined
![image](https://user-images.githubusercontent.com/194400/31310279-2a494bec-ab8d-11e7-97ec-6279ed9d09ab.png)

🙄

**Comment by nelsonic** [comment]
Of the 284k GitHub users "Hansel" is monitoring **23** have the word `undefined` in their username: 
![image](https://user-images.githubusercontent.com/194400/31310571-1e8315e0-ab92-11e7-9174-0660dfb4ca53.png)

Why do people need to be _difficult_!!

**Comment by nelsonic** [comment]
the _current_ test: 
https://github.com/nelsonic/github-scraper/blob/4c53e804196af546e3899ecb1e92fe3adfc01c45/test/url_validator.test.js#L25-L31
Does not have any _context_ ...
So I'm going to _update_ it!
The benefits of being the "_only user_" of this module is that I can make changes. 😉

**Comment by nelsonic** [comment]
the `undefined` user is a _legit_ person:
![image](https://user-images.githubusercontent.com/194400/31310822-adf69586-ab96-11e7-9453-f70e182cc363.png)
